name: Build, lint and test

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install
        run: npm install && npm run bootstrap
      - name: lint
        run: npm run lint
