name: Build, lint and test

on: [pull_request, workflow_dispatch]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm ci
